# Generated by Django 2.1.2 on 2018-12-14 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='动作类型')),
                ('description', models.CharField(max_length=500, verbose_name='动作描述')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=100, verbose_name='合同名称')),
                ('party_a_name', models.CharField(max_length=50, verbose_name='合同甲方名称')),
                ('party_b_name', models.CharField(max_length=50, verbose_name='合同乙方名称')),
                ('contract_content', models.TextField(verbose_name='合同内容')),
            ],
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_template_name', models.CharField(max_length=20, verbose_name='模板名称')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.Company', verbose_name='模板隶属公司')),
                ('requesters', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='可发起工作流的职员')),
            ],
            options={
                'verbose_name': '工作流模板',
                'verbose_name_plural': '工作流模板',
            },
        ),
        migrations.CreateModel(
            name='FlowTemplateStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=50, verbose_name='步骤名称')),
                ('work_mode', models.CharField(choices=[('or', 'or'), ('and', 'and')], default='or', max_length=3, verbose_name='工作模式')),
                ('no', models.SmallIntegerField(verbose_name='序号')),
                ('flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.FlowTemplate', verbose_name='隶属模板')),
                ('operators', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='参与人')),
            ],
            options={
                'verbose_name': '工作流模板步骤',
                'verbose_name_plural': '工作流模板步骤',
                'ordering': ['flow_template', 'no'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='流程标题')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.Company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_process', to=settings.AUTH_USER_MODEL)),
                ('updator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_process', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='流程步骤名称')),
                ('work_mode', models.CharField(choices=[('or', 'or'), ('and', 'and')], default='or', max_length=3)),
                ('active', models.BooleanField(default=False, verbose_name='是否是当前状态')),
                ('operators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Process')),
            ],
        ),
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='状态名称')),
                ('description', models.CharField(max_length=500, verbose_name='状态描述')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.ActionType')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_state_transition', to='workflow.State')),
                ('next_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_state_transition', to='workflow.State')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Process')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='state_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.StateType'),
        ),
        migrations.AddField(
            model_name='contract',
            name='process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflow.Process'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.ActionType'),
        ),
        migrations.AddField(
            model_name='action',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Process'),
        ),
        migrations.AddField(
            model_name='action',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Transition'),
        ),
    ]
