# Generated by Django 2.1.2 on 2018-12-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_state_transition', to='workflow.State'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='next_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_state_transition', to='workflow.State'),
        ),
    ]
