# Generated by Django 2.1.2 on 2018-12-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20181214_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='备注'),
        ),
    ]
