# Generated by Django 2.1.2 on 2018-12-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20181217_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-updated_time', '-created_time']},
        ),
    ]
